### ISSUE TITLE
Erreur sur connect (version UI sur Ubuntu)

### ISSUE THREAD

**Issue by chico3375** [dgalland/yart#1]
J'ai porté la dernière version de l'UI sur PC Ubuntu 18.04...l'appli. GUIControl TelecineApplication.py se lance bien...côté Raspberry pgpiod et Controller.py sont lancés...Mais à la connexion une erreur apparait :+1: 
ImageThread started
ImageThread connected
ImageThread terminated
<class 'AttributeError'>
'NoneType' object has no attribute 'decode'
<traceback object at 0x7ff10c92cc88>
Traceback (most recent call last):
  File "TelecineApplication.py", line 471, in connectDisconnect
    self.connect()
  File "TelecineApplication.py", line 486, in connect
    self.getMotorSettings()
  File "TelecineApplication.py", line 148, in getMotorSettings
    settings = self.sock.receiveObject()
  File "../Common/MessageSocket.py", line 71, in receiveObject
    s = self.receiveString()
  File "../Common/MessageSocket.py", line 59, in receiveString
    return self.receiveMsg().decode()
AttributeError: 'NoneType' object has no attribute 'decode'

et côté Raspberry :+1: 
pi@raspberrypi3Camera:~/yart-master/Raspberry $ python3 Controller.py
Command sock connected
Image sock connected
SendImageThread started
Command:0x4

SendImageThread terminated
Stop
Traceback (most recent call last):
  File "Controller.py", line 409, in <module>
    elif command == TAKE_BGR:
NameError: name 'TAKE_BGR' is not defined

**Comment by chico3375** [comment]
With  the 30th sept. update in Common, Connect is working...but..
après open la commande shot provoque une
Erreur de segmentation sur le PC Ubuntu 18.04LTS.
Sur le Rapberry :
pi@raspberrypi3Camera:~/yart-master/Raspberry $ python3 Controller.py
Command sock connected
Image sock connected
SendImageThread started
Command:0x4

Command:0xf

CaptureThread started
Command:0x3

Command:0x5

Command:0xc

Command:0xc

Command:0x5

Command:0xc

Command:0x5

Command:0x0

SendImageThread terminated
Stop
Traceback (most recent call last):
  File "Controller.py", line 402, in <module>
    request = commandSock.receiveObject()
  File "../Common/MessageSocket.py", line 71, in receiveObject
    s = self.receiveString()
  File "../Common/MessageSocket.py", line 59, in receiveString
    return self.receiveMsg().decode()
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by chico3375** [comment]
Logiciels installés :+1: 
sur le Raspberry 3 B+ :+1: 
Python 3.5.3
Picamera 1.13.1b0
numpy 1.16.2
pip 19.2.3
pigpio 41.44
Sur UBUNTU 18.04 LTS :+1: 
Python 3.6.8
pip 19.2.3 
numpy 1.16.2
PyQt5           5.13.1
PyQt5-sip       4.19.19
matplotlib      3.1.1
opencv-python   4.1.1.26

Après Connect, puis open 
à la commande Analyse de lens analyse, message d'erreur suivant sur le PC :
ImageThread started
ImageThread connected
ImageThread terminated
<class 'TypeError'>
receiveArray() takes 0 positional arguments but 1 was given
<traceback object at 0x7f73b1d13ac8>
Traceback (most recent call last):
  File "/home/alain/Téléchargements/yart-master/GUIControl/ImageThread.py", line 190, in run
    self.lensAnalyze(header)
  File "/home/alain/Téléchargements/yart-master/GUIControl/ImageThread.py", line 124, in lensAnalyze
    image = self.imageSock.receiveArray()  #bgr
TypeError: receiveArray() takes 0 positional arguments but 1 was given

et sur le Raspberry :+1: 

(cv) pi@raspberrypi3Camera:~/yart-master/Raspberry $ python Controller.py
Command sock connected
Image sock connected
SendImageThread started
Command:0x4

Command:0xf

CaptureThread started
Command:0x3

Command:0x5

Command:0xc

Command:0xc

Command:0x5

Command:0xc

Command:0x17

/home/pi/.virtualenvs/cv/local/lib/python3.5/site-packages/picamera/encoders.py:521: PiCameraAlphaStripping: using alpha-stripping to convert to non-alpha format; you may find the equivalent alpha format faster
  "using alpha-stripping to convert to non-alpha "
/home/pi/.virtualenvs/cv/local/lib/python3.5/site-packages/picamera/encoders.py:544: PiCameraResolutionRounded: frame size rounded up from 2592x1944 to 2592x1952
  width, height, fwidth, fheight)))
sended
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "Controller.py", line 284, in run
    imageSock.sendArray(object)
  File "../Common/MessageSocket.py", line 78, in sendArray
    self.socket.sendall(array.tobyes())
AttributeError: 'numpy.ndarray' object has no attribute 'tobyes'

**Comment by chico3375** [comment]
Ave le GUI sur Windows, la commande shot fonctionne ...Cette version n'est pas compatible avec Linux !

**Comment by chico3375** [comment]
Pourrais-je avoir accès à votre forum sur Google ?
Merci
